"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from ._app import (
    Klein,
    KleinErrorHandler,
    KleinRenderable,
    KleinRouteHandler,
    handle_errors,
    route,
    run,
    subroute,
    url_for,
    urlFor,
)
from ._dihttp import RequestComponent, RequestURL, Response
from ._form import Field, FieldValues, Form, RenderableForm
from ._plating import Plating
from ._requirer import Requirer
from ._session import Authorization, SessionProcurer
from ._version import __version__ as _incremental_version
from .resource import _SpecialModuleObject

if TYPE_CHECKING:
    resource = ...
else: ...
__all__ = (
    "Klein",
    "KleinErrorHandler",
    "KleinRenderable",
    "KleinRouteHandler",
    "Plating",
    "Field",
    "FieldValues",
    "Form",
    "RequestComponent",
    "RequestURL",
    "Response",
    "RenderableForm",
    "SessionProcurer",
    "Authorization",
    "Requirer",
    "__author__",
    "__copyright__",
    "__license__",
    "__version__",
    "handle_errors",
    "resource",
    "route",
    "run",
    "subroute",
    "urlFor",
    "url_for",
)
__version__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
