"""
This type stub file was generated by pyright.
"""

from typing import AnyStr, Iterable

from zope.interface import implementer

from attr import attrs
from twisted.web.http_headers import Headers

from ._headers import IMutableHTTPHeaders, RawHeaders, String

"""
Support for interoperability with L{twisted.web.http_headers.Headers}.
"""
__all__ = ()

@implementer(IMutableHTTPHeaders)
@attrs(frozen=True)
class HTTPHeadersWrappingHeaders:
    """
    HTTP entity headers.

    This is an L{IMutableHTTPHeaders} implementation that wraps a L{Headers}
    object.
    """

    _headers: Headers = ...
    @property
    def rawHeaders(self) -> RawHeaders: ...
    def getValues(self, name: AnyStr) -> Iterable[AnyStr]: ...
    def remove(self, name: String) -> None: ...
    def addValue(self, name: AnyStr, value: AnyStr) -> None: ...
