"""
This type stub file was generated by pyright.
"""

class ValidationError(Exception):
    """
    A L{ValidationError} is raised by L{Field.extractValue}.
    """

    def __init__(self, message: object) -> None:
        """
        Initialize a L{ValidationError} with a message to show to the user.
        """
        ...

class ValueAbsent(ValidationError):
    """
    A value was required but none was supplied.
    """

    ...
