"""
This type stub file was generated by pyright.
"""

from typing import Mapping, Optional, Union

from zope.interface import Interface

"""
Internal interface definitions.

All Zope Interface classes should be imported from here so that type checking
works, since mypy doesn't otherwise get along with Zope Interface.
"""
KleinQueryValue = Union[str, int, float]

class IKleinRequest(Interface):
    branch_segments = ...
    mapper = ...
    def url_for(
        endpoint: str,
        values: Optional[Mapping[str, KleinQueryValue]] = ...,
        method: Optional[str] = ...,
        force_external: bool = ...,
        append_unknown: bool = ...,
    ) -> str:
        """
        L{werkzeug.routing.MapAdapter.build}
        """
        ...

__all__ = ()
