"""
This type stub file was generated by pyright.
"""

from typing import Union

from zope.interface import implementer

from attr import attrs
from tubes.itube import IFount

from ._imessage import IHTTPHeaders, IHTTPResponse
from ._message import MessageState

"""
HTTP response API.
"""
__all__ = ()

@implementer(IHTTPResponse)
@attrs(frozen=True)
class FrozenHTTPResponse:
    """
    Immutable HTTP response.
    """

    status: int = ...
    headers: IHTTPHeaders = ...
    _body: Union[bytes, IFount] = ...
    _state: MessageState = ...
    def bodyAsFount(self) -> IFount: ...
    async def bodyAsBytes(self) -> bytes: ...
