"""
This type stub file was generated by pyright.
"""

from typing import Any, BinaryIO

from zope.interface import implementer

from attr import attrs
from tubes.itube import IDrain, IFount, ISegment

"""
Extensions to Tubes.
"""
__all__ = ()

async def fountToBytes(fount: IFount) -> bytes: ...
def bytesToFount(data: bytes) -> IFount: ...
@implementer(IFount)
@attrs(frozen=False)
class IOFount:
    """
    Fount that reads from a file-like-object.
    """

    outputType = ISegment
    _source: BinaryIO = ...
    drain: IDrain = ...
    _paused = ...
    def __attrs_post_init__(self) -> None: ...
    def flowTo(self, drain: IDrain) -> IFount: ...
    def pauseFlow(self) -> Any: ...
    def stopFlow(self) -> Any: ...
