"""
This type stub file was generated by pyright.
"""

__all__ = (
    "Klein",
    "KleinRequest",
    "handle_errors",
    "resource",
    "route",
    "run",
    "subroute",
    "urlFor",
    "url_for",
)
