"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Union

from ._resource import KleinResource as _KleinResource

"""
This module, L{klein.resource}, serves two purposes:

    - It's the global C{resource()} method on the global L{klein.Klein}
      application.

    - It's the module where L{KleinResource} is defined.
"""
KleinResource = _KleinResource

class _SpecialModuleObject:
    """
    See the test in
    L{klein.test.test_resource.GlobalAppTests.test_weird_resource_situation}
    for an explanation.
    """

    __all__ = ("KleinResource", "ensure_utf8_bytes")
    KleinResource = _KleinResource
    def __init__(self, preserve: Any) -> None: ...
    @property
    def ensure_utf8_bytes(self) -> Callable[[Union[str, bytes]], bytes]: ...
    def __call__(self) -> _KleinResource:
        """
        Return an L{IResource} which suitably wraps this app.

        @returns: An L{IResource}
        """
        ...
    def __repr__(self) -> str:
        """
        Give a special C{repr()} to make the dual purpose of this object clear.
        """
        ...

module = ...
