services:
  - name: Data Center Light
    label: dcl  # Must match the 'service' label in the Prometheus alerts
    description: |
      Our VM hosting: datacenterlight.ch, devuanhosting.com, ipv6onlyhosting.com

    components:
      - name: Storage
        description: Our redundant cluster that keeps your data safe
        label: storage  # Must match the 'component' label in the Prometheus alerts

      - name: Network Connectivity
        description: blah blah something something
        label: network

      - name: Virtual machines
        description: Health of the virtual machines hosted in DCL
        label: vms


branding:
  colors:
    primary:   '#073642'
    secondary: '#268bd2'
    green:     '#859900'
    orange:    '#cb4b16'
    red:       '#dc322f'
  # TODO logo
