title: ungleich≠ status
url: https://ungleich.ch

services:
  - name: Data Center Light
    url: https://datacenterlight.ch
    label: dcl  # Must match the 'service' label in the Prometheus alerts
    description: |
      Our VM hosting: datacenterlight.ch, devuanhosting.com, ipv6onlyhosting.com

    components:
      - name: Storage
        description: Our redundant cluster that keeps your data safe
        label: storage  # Must match the 'component' label in the Prometheus alerts

      - name: Network Connectivity
        description: blah blah something something
        label: network

      - name: Virtual machines
        description: Health of the virtual machines hosted in DCL
        label: vms

  - name: Glarnercloud
    url: https://ungleich.ch/de/cms/glarnercloud/
    label: glarner  # Must match the 'service' label in the Prometheus alerts
    description: |
      Our hosted NextCloud instances

    components:
      - name: Storage
        description: Our redundant cluster that keeps your data safe
        label: storage  # Must match the 'component' label in the Prometheus alerts

      - name: Network Connectivity
        description: blah blah something something
        label: network

  - name: Internetz for Glarus
    url: https://ungleich.ch/glasfaser
    label: ispstuff # Must match the 'service' label in the Prometheus alerts
    description: |
      Have good internetz in Glarus!

    components:
      - name: Network Connectivity
        description: blah blah something something
        label: network



branding:
  colors:
    primary:   '#073642'
    secondary: '#268bd2'
    green:     '#859900'
    orange:    '#cb4b16'
    red:       '#dc322f'
  # TODO logo

# Note you need to add your keys in authorized_keys format to:
#   SSH_KEYS_DIR/USER.key
ssh_users:
  - testuser
