variables:
  pyimage: &pyimage 'python:3.11-slim-bullseye'
  pysteps: &pysteps
   - pip install pipenv
   - pipenv install --dev
  pyenv: &pyenv
    - PYTHONPATH=./src
    - MYPYPATH=./src

steps:
  black:
    image: *pyimage
    group: linters
    commands:
      - <<: *pysteps
      - pipenv run black src --check
    environment: *pyenv
  flake8:
    image: *pyimage
    group: linters
    commands:
      - <<: *pysteps
      - pipenv run flake8 src
    environment: *pyenv
  mypy:
    image: *pyimage
    group: linters
    commands:
      - <<: *pysteps
      - pipenv run mypy -m adlermanager
    environment: *pyenv
  dotenv:
    image: *pyimage
    group: linters
    commands:
      - <<: *pysteps
      - pipenv run python -m adlermanager.Config dotenv.example.gen
      - diff -q dotenv.example dotenv.example.gen
    environment: *pyenv
